### ISSUE TITLE
Can you clean up the zip and simplify the readme?

### ISSUE THREAD

**Issue by mikeloeven** [StarCrusher96/Kerbal-Star-Systems#1]
Any chance of reorganizing the zip folder to make installation a bit less tedious. The sub-folders are really not needed as all the steps can be detailed in a single read-me file including a list of what is required and what is optional. Ill admit your instructions are good for someone who is completely computer illiterate however for most people it makes the installation take much longer due to having to sort through the sub-folders.

**Comment by StarCrusher96** [comment]
Done for 0.6
