### ISSUE TITLE
Support for CKAN

### ISSUE THREAD

**Issue by brezinajn** [StarCrusher96/Kerbal-Star-Systems#2]
It would be nice to be able to install this through CKAN :)
Keep up great work :)

**Comment by Olympic1** [comment]
If @StarCrusher96 is ok with it that KSS may be added to CKAN, you can open a request over there. https://github.com/KSP-CKAN/NetKAN/issues

**Comment by StarCrusher96** [comment]
I dont give permission to add KSS to CKAN.
